version: '3'

services:
  mysql:
    container_name: house_server_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "house_server"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "house_server"
      MYSQL_PASSWORD: "house_password"
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
