spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/house_server
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: house_server
    password: house_password
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: ALWAYS
external:
  apartment-api:
    path: http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev
    service-key: ""
server:
  port: 8090

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2
